categories/index.html

<fix> fixed issue #60

---

README.md

<doc> added badges in readme

---

notes/Algorithm/hash_map/chinese/index.html

issue #74  work in progress
- needs more example & some diagrams might help?

new branch -- issue #74

---

notes/Algorithm/hash_map/chinese/index.html

issue #70 WIP
TODO: 
- Open Addressing to be explained
- Classic HashMap Questions Collection

<feat> start working on open addressing

---

notes/Algorithm/hash_map/english/index.html

- translated principal session

---

notes/Algorithm/hash_map/english/index.html

- translated hash collision session

---

notes/Algorithm/hash_map/english/index.html

- translated seperate chaining constraint session

---

notes/Algorithm/hash_map/english/index.html

- translated open addressing session

---

notes/Algorithm/hash_map/english/index.html

- translated B&R tree session

---

notes/Algorithm/hash_map/english/index.html

- translated evaluation session

---

notes/Algorithm/hash_map/english/index.html

- translated reference session

---

categories/index.html
notes/index.html

<feat> add entry for chinese note of hash map

---

categories/index.html
notes/index.html

<feat> added entry for english notes of hash map

---

notes/index.html

<fix> changed the note count in notes page

---

notes/Algorithm/hash_map/chinese/index.html

<feat> added the question list in hashmap chinese notes

---

notes/Algorithm/hash_map/english/index.html

<feat> added the question list to hash map english notes

---

notes/Algorithm/hash_map/english/index.html

<fix> some typos fixed

---

notes/Algorithm/hash_map/chinese/index.html

<fix> fixed issue #124

---

notes/Algorithm/hash_map/english/index.html

<fix> fixed issue #125

---

notes/Algorithm/hash_map/chinese/index.html

<fix> fixed issue #126

---

notes/Algorithm/hash_map/english/index.html

<fix> fixed issue #127

---

notes/Algorithm/linked_list/chinese/index.html

Issue #108  Start Working On It.

[newbranch] start working linked list notes

---

categories/index.html
notes/index.html

- added the entry to the chinese notes of linked list

---

notes/index.html

- fixed issue #134

---

notes/Algorithm/linked_list/chinese/index.html

- added more information

---

notes/Algorithm/linked_list/english/index.html

Issue #109 Start Working On It

- start working on english notes of linked list

---

notes/Algorithm/linked_list/english/index.html

F linked list en

---

categories/index.html

- fixed the entry order issue

---

notes/Algorithm/array/chinese/index.html
notes/Algorithm/array/english/index.html
notes/Algorithm/backtracking/chinese/index.html

Fix issue 116

---

notes/Algorithm/sort/chinese/index.html
notes/Algorithm/sort/english/index.html

Fix issue 117

---

notes/Algorithm/bisection/chinese/index.html
notes/Algorithm/bisection/english/index.html

Fix issue 118

---

notes/Algorithm/divide_and_conquer/chinese/index.html

Fix issue 119

---

notes/Algorithm/hash_map/chinese/index.html
notes/Algorithm/hash_map/english/index.html

Fix issue 121

---

notes/Algorithm/twopointer/english/index.html

- fixed issue #122 (2/2)

---

notes/Algorithm/unionfind/chinese/index.html
notes/Algorithm/unionfind/english/index.html

Fix issue 123

---

notes/Algorithm/linked_list/chinese/index.html
notes/Algorithm/linked_list/english/index.html

Fix issue 167

---

notes/Algorithm/backtracking/chinese/index.html
notes/Algorithm/backtracking/english/index.html

Fix issue 171

---

notes/Algorithm/greedy/chinese/index.html
notes/Algorithm/greedy/english/index.html

Fix issue 172

---

notes/Algorithm/string/chinese/index.html

F issue 144

---

categories/index.html
notes/index.html

F issue 199

---

categories/index.html
notes/index.html

F issue 201
